## STATIC CONFIGURATION
global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"
  metrics:
    address: ":8081"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
